### PR TITLE
rm gwasglue2 functions

### PR DESCRIPTION
**Pull request by ritarasteiro**
Start preparing resubmission.
- rm all functions  related with `gwasglue2`

### CODE REVIEW

**Comment by ritarasteiro** [comment]
@explodecomputer  I rm all mentions of `gwasglue2` from this branch.  I also added a  [gwasglue2](https://github.com/MRCIEU/ieugwasr/tree/gwasglue2) branch with all `gwasglue2` functionalities.

**Comment by remlapmot** [comment]
In last week's commits @explodecomputer used an anonymous function in zzz.R on lin 53

https://github.com/MRCIEU/ieugwasr/blob/83f47ddfdfc1c3b8fc2326903d51ed1312075777/R/zzz.R#L53

Anonymous functions were only introduced in R 4.1.0 . So either we need to fix that back to a standard function call or bump the version of R in the DESCRIPTION to 4.1.0. My preference is to use a standard function here.

**Comment by remlapmot** [comment]
Great news it seems CRAN accepted a resubmission Gib <https://cran.r-project.org/package=ieugwasr> well done!

But is the version on master the version that was accepted? I'm guessing maybe not as the accepted CRAN version says 0.2.0 and master says 0.1.8.

So we need to get the accepted version onto master. And add the appropriate git tag and do a GitHub release. Is it up to commit https://github.com/MRCIEU/ieugwasr/pull/57/commits/72ed9e93e0b2da703b0638c94b6bbef0d42df9e0 that is the CRAN version?

Then you can add commits subsequent to the accepted version into this PR (or an additional PR), as the package build is still broken on R 4.0.5 as I noted above so that simple fix needs adding (or the R version needs bumping).

**Comment by ritarasteiro** [comment]
Congratulations @explodecomputer!

**Comment by explodecomputer** [comment]
Many thanks @ritarasteiro @remlapmot 
I've created the releases for the 3 (!) versions that have been submitted to CRAN. Unfortunately there was really bad timing because of some issues with the new API, so 0.2.0 was pointing to that and became available on CRAN at exactly the wrong moment when that API version developed some problems, so I then submitted an updated version to 0.2.1 thinking it would be some time before that would be fixed but 2 days later it was fixed and I then submitted 0.2.2. So a bit of a mess!

I've fixed the anonymous function issue now also thanks for spotting that! And codecov seems to have started working again, I don't know why.

**Comment by explodecomputer** [comment]
Many thanks @ritarasteiro @remlapmot 
I've created the releases for the 3 (!) versions that have been submitted to CRAN. Unfortunately there was really bad timing because of some issues with the new API, so 0.2.0 was pointing to that and became available on CRAN at exactly the wrong moment when that API version developed some problems, so I then submitted an updated version to 0.2.1 thinking it would be some time before that would be fixed but 2 days later it was fixed and I then submitted 0.2.2. So a bit of a mess!

I've fixed the anonymous function issue now also thanks for spotting that! And codecov seems to have started working again, I don't know why.

**Comment by remlapmot** [comment]
Also for packages on CRAN for the pkgdown site it's good to turn on pkgdown's development mode <https://pkgdown.r-lib.org/reference/build_site.html?q=mode#development-mode>.

To do this to *_pkgdown.yml* simply add these 2 lines

```yaml
development:
  mode: auto
```

Then the main site will be for versions with release numbers, and there will be a dev subdirectoty in the site with the pages for the development version.

**Comment by remlapmot** [comment]
To show you what you get with development mode set to `auto`:

* main site for released version: https://remlapmot.github.io/OneSampleMR/
* site in dev subdirectoty for development version: https://remlapmot.github.io/OneSampleMR/dev/

done automagically by pkgdown 🪄

**Pull request merged**
